codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        threshold: 0.4
        if_not_found: success

ignore:
  - "**/riverAsymmetry" # ignore WIP
